//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrePullImage) DeepCopyInto(out *PrePullImage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrePullImage.
func (in *PrePullImage) DeepCopy() *PrePullImage {
	if in == nil {
		return nil
	}
	out := new(PrePullImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrePullImage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrePullImageList) DeepCopyInto(out *PrePullImageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PrePullImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrePullImageList.
func (in *PrePullImageList) DeepCopy() *PrePullImageList {
	if in == nil {
		return nil
	}
	out := new(PrePullImageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrePullImageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrePullImageSpec) DeepCopyInto(out *PrePullImageSpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrePullImageSpec.
func (in *PrePullImageSpec) DeepCopy() *PrePullImageSpec {
	if in == nil {
		return nil
	}
	out := new(PrePullImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrePullImageStateOnNode) DeepCopyInto(out *PrePullImageStateOnNode) {
	*out = *in
	out.NodeRef = in.NodeRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrePullImageStateOnNode.
func (in *PrePullImageStateOnNode) DeepCopy() *PrePullImageStateOnNode {
	if in == nil {
		return nil
	}
	out := new(PrePullImageStateOnNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrePullImageStatus) DeepCopyInto(out *PrePullImageStatus) {
	*out = *in
	out.DaemonSetRef = in.DaemonSetRef
	if in.PerNodeState != nil {
		in, out := &in.PerNodeState, &out.PerNodeState
		*out = make([]PrePullImageStateOnNode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrePullImageStatus.
func (in *PrePullImageStatus) DeepCopy() *PrePullImageStatus {
	if in == nil {
		return nil
	}
	out := new(PrePullImageStatus)
	in.DeepCopyInto(out)
	return out
}
