/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/Cdayz/k8s-image-pre-puller/pkg/apis/images/v1"
	scheme "github.com/Cdayz/k8s-image-pre-puller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PrePullImagesGetter has a method to return a PrePullImageInterface.
// A group's client should implement this interface.
type PrePullImagesGetter interface {
	PrePullImages(namespace string) PrePullImageInterface
}

// PrePullImageInterface has methods to work with PrePullImage resources.
type PrePullImageInterface interface {
	Create(ctx context.Context, prePullImage *v1.PrePullImage, opts metav1.CreateOptions) (*v1.PrePullImage, error)
	Update(ctx context.Context, prePullImage *v1.PrePullImage, opts metav1.UpdateOptions) (*v1.PrePullImage, error)
	UpdateStatus(ctx context.Context, prePullImage *v1.PrePullImage, opts metav1.UpdateOptions) (*v1.PrePullImage, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.PrePullImage, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.PrePullImageList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.PrePullImage, err error)
	PrePullImageExpansion
}

// prePullImages implements PrePullImageInterface
type prePullImages struct {
	client rest.Interface
	ns     string
}

// newPrePullImages returns a PrePullImages
func newPrePullImages(c *ImagesV1Client, namespace string) *prePullImages {
	return &prePullImages{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the prePullImage, and returns the corresponding prePullImage object, and an error if there is any.
func (c *prePullImages) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.PrePullImage, err error) {
	result = &v1.PrePullImage{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("prepullimages").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PrePullImages that match those selectors.
func (c *prePullImages) List(ctx context.Context, opts metav1.ListOptions) (result *v1.PrePullImageList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.PrePullImageList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("prepullimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested prePullImages.
func (c *prePullImages) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("prepullimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a prePullImage and creates it.  Returns the server's representation of the prePullImage, and an error, if there is any.
func (c *prePullImages) Create(ctx context.Context, prePullImage *v1.PrePullImage, opts metav1.CreateOptions) (result *v1.PrePullImage, err error) {
	result = &v1.PrePullImage{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("prepullimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(prePullImage).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a prePullImage and updates it. Returns the server's representation of the prePullImage, and an error, if there is any.
func (c *prePullImages) Update(ctx context.Context, prePullImage *v1.PrePullImage, opts metav1.UpdateOptions) (result *v1.PrePullImage, err error) {
	result = &v1.PrePullImage{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("prepullimages").
		Name(prePullImage.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(prePullImage).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *prePullImages) UpdateStatus(ctx context.Context, prePullImage *v1.PrePullImage, opts metav1.UpdateOptions) (result *v1.PrePullImage, err error) {
	result = &v1.PrePullImage{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("prepullimages").
		Name(prePullImage.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(prePullImage).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the prePullImage and deletes it. Returns an error if one occurs.
func (c *prePullImages) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("prepullimages").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *prePullImages) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("prepullimages").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched prePullImage.
func (c *prePullImages) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.PrePullImage, err error) {
	result = &v1.PrePullImage{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("prepullimages").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
