# permissions for end users to edit prepullimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: prepullimage-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-image-pre-puller
    app.kubernetes.io/part-of: k8s-image-pre-puller
    app.kubernetes.io/managed-by: kustomize
  name: prepullimage-editor-role
rules:
- apiGroups:
  - cdayz.k8s.extensions.cdayz.k8s.extensions
  resources:
  - prepullimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cdayz.k8s.extensions.cdayz.k8s.extensions
  resources:
  - prepullimages/status
  verbs:
  - get
