---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - images.cdayz.k8s.extensions
  resources:
  - prepullimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - images.cdayz.k8s.extensions
  resources:
  - prepullimages/finalizers
  verbs:
  - update
- apiGroups:
  - images.cdayz.k8s.extensions
  resources:
  - prepullimages/status
  verbs:
  - get
  - patch
  - update
