apiVersion: cdayz.k8s.extensions.cdayz.k8s.extensions/v1
kind: PrePullImage
metadata:
  labels:
    app.kubernetes.io/name: prepullimage
    app.kubernetes.io/instance: prepullimage-sample
    app.kubernetes.io/part-of: k8s-image-pre-puller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-image-pre-puller
  name: prepullimage-sample
spec:
  # TODO(user): Add fields here
