---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prepullimages.images.cdayz.k8s.extensions
spec:
  group: images.cdayz.k8s.extensions
  names:
    kind: PrePullImage
    listKind: PrePullImageList
    plural: prepullimages
    singular: prepullimage
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: PrePullImage is the Schema for the prepullimages API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: PrePullImageSpec defines the desired state of PrePullImage
            properties:
              image:
                description: Image which should be pulled on nodes
                type: string
              nodeSelector:
                additionalProperties:
                  type: string
                description: NodeSelector for selecting only particular nodes where
                  image should be pre-pulled
                type: object
            required:
            - image
            - nodeSelector
            type: object
          status:
            description: PrePullImageStatus defines the observed state of PrePullImage
            type: object
        type: object
    subresources:
      status: {}