/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	imagesv1 "github.com/Cdayz/k8s-image-pre-puller/pkg/apis/images/v1"
	versioned "github.com/Cdayz/k8s-image-pre-puller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/Cdayz/k8s-image-pre-puller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/Cdayz/k8s-image-pre-puller/pkg/client/listers/images/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PrePullImageInformer provides access to a shared informer and lister for
// PrePullImages.
type PrePullImageInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.PrePullImageLister
}

type prePullImageInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPrePullImageInformer constructs a new informer for PrePullImage type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPrePullImageInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPrePullImageInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPrePullImageInformer constructs a new informer for PrePullImage type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPrePullImageInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ImagesV1().PrePullImages(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ImagesV1().PrePullImages(namespace).Watch(context.TODO(), options)
			},
		},
		&imagesv1.PrePullImage{},
		resyncPeriod,
		indexers,
	)
}

func (f *prePullImageInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPrePullImageInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *prePullImageInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&imagesv1.PrePullImage{}, f.defaultInformer)
}

func (f *prePullImageInformer) Lister() v1.PrePullImageLister {
	return v1.NewPrePullImageLister(f.Informer().GetIndexer())
}
