/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/Cdayz/k8s-image-pre-puller/pkg/apis/images/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePrePullImages implements PrePullImageInterface
type FakePrePullImages struct {
	Fake *FakeImagesV1
	ns   string
}

var prepullimagesResource = v1.SchemeGroupVersion.WithResource("prepullimages")

var prepullimagesKind = v1.SchemeGroupVersion.WithKind("PrePullImage")

// Get takes name of the prePullImage, and returns the corresponding prePullImage object, and an error if there is any.
func (c *FakePrePullImages) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.PrePullImage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(prepullimagesResource, c.ns, name), &v1.PrePullImage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.PrePullImage), err
}

// List takes label and field selectors, and returns the list of PrePullImages that match those selectors.
func (c *FakePrePullImages) List(ctx context.Context, opts metav1.ListOptions) (result *v1.PrePullImageList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(prepullimagesResource, prepullimagesKind, c.ns, opts), &v1.PrePullImageList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.PrePullImageList{ListMeta: obj.(*v1.PrePullImageList).ListMeta}
	for _, item := range obj.(*v1.PrePullImageList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested prePullImages.
func (c *FakePrePullImages) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(prepullimagesResource, c.ns, opts))

}

// Create takes the representation of a prePullImage and creates it.  Returns the server's representation of the prePullImage, and an error, if there is any.
func (c *FakePrePullImages) Create(ctx context.Context, prePullImage *v1.PrePullImage, opts metav1.CreateOptions) (result *v1.PrePullImage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(prepullimagesResource, c.ns, prePullImage), &v1.PrePullImage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.PrePullImage), err
}

// Update takes the representation of a prePullImage and updates it. Returns the server's representation of the prePullImage, and an error, if there is any.
func (c *FakePrePullImages) Update(ctx context.Context, prePullImage *v1.PrePullImage, opts metav1.UpdateOptions) (result *v1.PrePullImage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(prepullimagesResource, c.ns, prePullImage), &v1.PrePullImage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.PrePullImage), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePrePullImages) UpdateStatus(ctx context.Context, prePullImage *v1.PrePullImage, opts metav1.UpdateOptions) (*v1.PrePullImage, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(prepullimagesResource, "status", c.ns, prePullImage), &v1.PrePullImage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.PrePullImage), err
}

// Delete takes name of the prePullImage and deletes it. Returns an error if one occurs.
func (c *FakePrePullImages) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(prepullimagesResource, c.ns, name, opts), &v1.PrePullImage{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePrePullImages) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(prepullimagesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.PrePullImageList{})
	return err
}

// Patch applies the patch and returns the patched prePullImage.
func (c *FakePrePullImages) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.PrePullImage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(prepullimagesResource, c.ns, name, pt, data, subresources...), &v1.PrePullImage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.PrePullImage), err
}
