apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "{{ .Values.metrics.path }}"
    prometheus.io/port: "{{ .Values.metrics.port }}"
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-service
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}-app
    release: {{ .Release.Name }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
    - name: profiling
      port: {{ .Values.profiling.port }}
      targetPort: {{ .Values.profiling.port }}
