apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: k8s-image-pre-puller
    app.kubernetes.io/version: "{{ .Values.image.tag }}"
