name: go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Download go modules
      run: go mod download

    - name: Generate code
      run: bash scripts/update-codegen.sh

    - name: Validate there are no changes
      run: |
        git status --porcelain
        export code=$(git status --porcelain | wc -l)
        exit $code

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
